### ISSUE TITLE
Return values

### ISSUE THREAD

**Issue by veltzerdoron** [Faylixe/googlecodejam-cli#7]
I'm running this from an automation python script which always gets the same return value (0) whether the submission passed or failed, this could be as a result of running it through the JVM? does the program return the success of the submission?

**Comment by Faylixe** [comment]
Hum I didn't setup any return code relative to the submission status. I
just print the result in stdin. But that makes senses, I will update it
today.

Le vendredi 29 avril 2016, vetlzerdoron notifications@github.com a écrit :

> I'm running this from an automation python script which always gets the
> same return value (0) whether the submission passed or failed, this could
> be as a result of running it through the JVM? does the program return the
> success of the submission?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Faylixe/googlecodejam-cli/issues/7

## 

---

_Félix Voituret_
_Research and development engineer_
_iSmart, SmartLab, Kware_
_www.ismart.fr http://www.ismart.fr_
Phone : +33 6 48 95 75 46, Fax : +33 4 42 24 45 78

**Comment by Faylixe** [comment]
Pushed a new release **v1.3.2**, Error code -1 has been used for failed execution.

**Comment by veltzerdoron** [comment]
Merci beaucoup, fonctionne très bien
